version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${SECRET_KEY}
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: singlestore/cluster-in-a-box:latest
    environment:
      - LICENSE_KEY=${SINGLESTORE_LICENSE_KEY}
      - ROOT_PASSWORD=${DB_PASSWORD}
      - SINGLESTORE_DB=${DB_NAME}
      - SINGLESTORE_USER=${DB_USER}
      - SINGLESTORE_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
